export type Project = {
  slug: string
  title: string
  subtitle: string
  category: string        // space-separated: 'branding web design'
  cat: string             // display label for the badge
  image: string           // path relative to /public
  url?: string
  year: string
  country: string
  industry: string
  stack: string[]
  tags: string[]
  summary: string
  challenge: string
  solution: string
  results: string[]
}

export const PROJECTS: Project[] = [
  {
    slug: 'amc-group',
    title: 'AMC Group',
    subtitle: 'Real Estate · Cairo, Egypt · 2024',
    category: 'branding web design',
    cat: 'Branding & Web',
    image: '/work/amc-group.jpg',
    url: 'https://amc-group.net/',
    year: '2024',
    country: 'Egypt',
    industry: 'Real Estate',
    stack: ['Next.js', 'Tailwind CSS', 'Figma'],
    tags: ['Web Dev', 'Branding', 'Social Media', 'Graphic Design'],
    summary: 'Full brand identity and custom Next.js website for AMC Group, a real estate and investment company based in Cairo.',
    challenge: 'AMC Group needed a complete digital presence — from a brand identity that communicated authority and trust, to a high-performance website that could represent their properties portfolio professionally.',
    solution: 'We delivered a comprehensive brand system including logo, brand guidelines, and collateral, paired with a custom Next.js website built for speed and SEO. Ongoing social media and graphic design support was included.',
    results: [
      'Complete brand identity system delivered in 3 weeks',
      'Custom Next.js site with 95+ Lighthouse performance score',
      'Ongoing social media design retainer secured',
    ],
  },
  {
    slug: 'abdelfattah-site',
    title: 'Abdelfattah.site',
    subtitle: 'Personal Brand · Cairo, Egypt · 2025',
    category: 'branding web',
    cat: 'Personal Brand & Web',
    image: '/work/abdelfattah-site.jpg',
    url: 'https://abdelfattah.site/',
    year: '2025',
    country: 'Egypt',
    industry: 'Personal Brand',
    stack: ['Next.js', 'Figma'],
    tags: ['Web Dev', 'Branding', 'Next.js'],
    summary: 'Personal portfolio and brand site built with Next.js — fast, minimal, and engineered to convert.',
    challenge: 'Building a personal brand site that communicates technical depth while staying visually minimal and loading instantly.',
    solution: 'Designed and developed a fully custom Next.js portfolio with zero templates, focused on performance and clarity.',
    results: [
      'Sub-second page loads on Vercel edge network',
      '100/100 Lighthouse performance score',
      'Fully custom design and code — no templates',
    ],
  },
  {
    slug: 'german-mediators',
    title: 'German Mediators',
    subtitle: 'Legal Services · Germany · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/german-mediators.jpg',
    url: 'https://german-mediators.de/',
    year: '2024',
    country: 'Germany',
    industry: 'Legal & Mediation',
    stack: ['WordPress', 'Elementor', 'Polylang'],
    tags: ['Web Dev', 'WordPress', 'Multilingual'],
    summary: 'Multilingual WordPress website for a professional mediation firm in Germany, supporting both German and English audiences.',
    challenge: 'The firm needed a bilingual website that conveyed legal professionalism while being easy for non-technical staff to update and maintain.',
    solution: 'Built a clean, authoritative WordPress site with Polylang for DE/EN multilingual support, full SEO optimisation, and a simple backend for content management.',
    results: [
      'Bilingual DE/EN site launched on schedule',
      'Non-technical staff managing content independently within a week',
      'Organic search visibility improved within 60 days',
    ],
  },
  {
    slug: 'alnasr-modern',
    title: 'Al-Nasr Modern',
    subtitle: 'Manufacturing · Cairo, Egypt · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/alnasr-modern.jpg',
    url: 'https://www.alnasrmodern.com/',
    year: '2024',
    country: 'Egypt',
    industry: 'Manufacturing',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Corporate WordPress website for Al-Nasr Modern, a manufacturing company serving the Egyptian industrial sector.',
    challenge: 'Establishing a credible online presence for a traditional manufacturing business that had relied solely on word-of-mouth.',
    solution: 'Developed a professional corporate site with a clear services architecture, product showcase, and a contact system — all on a maintainable WordPress stack.',
    results: [
      'First professional website for the company',
      'Services and product catalogue clearly structured',
      'Mobile-responsive with optimised loading for Egyptian networks',
    ],
  },
  {
    slug: 'py-partners',
    title: 'PY Partners',
    subtitle: 'Professional Services · Sydney, Australia · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/py-partners.jpg',
    url: 'https://www.pypartners.com.au/',
    year: '2024',
    country: 'Australia',
    industry: 'Professional Services',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Professional services website for PY Partners, a Sydney-based consultancy firm.',
    challenge: 'PY Partners needed a refined, corporate-grade website that would hold up against larger competitors in the Australian professional services market.',
    solution: 'Built a clean, conversion-focused WordPress site that communicates expertise and trust, with a structured services layout and integrated contact flow.',
    results: [
      'Site live within 3 weeks of project start',
      'Competitive with Tier-1 consulting firm web standards',
      'Australian-market SEO and accessibility compliant',
    ],
  },
  {
    slug: 'juen-phie',
    title: 'Juen Phie',
    subtitle: 'Health & Wellness · Sydney, Australia · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/juen-phie.jpg',
    url: 'http://juenphie.com.au/',
    year: '2024',
    country: 'Australia',
    industry: 'Health & Wellness',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Wellness practitioner website for Juen Phie, a Sydney-based health professional offering personalised services.',
    challenge: 'Creating a warm, trustworthy online presence for a solo practitioner that clearly communicates services and drives appointment bookings.',
    solution: 'Developed a clean WordPress site with an intuitive layout, service details, and booking integration — calibrated for a personal, professional tone.',
    results: [
      'Booking inquiries via website within first week of launch',
      'Fully mobile-optimised for the Australian audience',
      'Easy content updates managed by the client',
    ],
  },
  {
    slug: 'pyp-training',
    title: 'PYP Training',
    subtitle: 'Online Education · International · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/pyp-training.jpg',
    url: 'https://pyptraining.online/',
    year: '2024',
    country: 'International',
    industry: 'E-Learning',
    stack: ['WordPress', 'LearnDash', 'WooCommerce'],
    tags: ['Web Dev', 'WordPress', 'LMS'],
    summary: 'Full LMS-powered e-learning platform for PYP Training, delivering international curriculum training online.',
    challenge: 'Building a scalable LMS that could handle structured course delivery, student management, and payments — all without custom development.',
    solution: 'Implemented a WordPress-based LMS using LearnDash and WooCommerce, with a clean interface, course catalogue, and secure payment processing.',
    results: [
      'Full LMS operational with 10+ courses at launch',
      'Student enrolment and payment flow end-to-end',
      'Platform scalable to hundreds of concurrent learners',
    ],
  },
  {
    slug: 'peak-pulse',
    title: 'Peak Pulse',
    subtitle: 'Sports & Fitness · Cairo, Egypt · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/peak-pulse.jpg',
    url: 'https://peakpulse.net/',
    year: '2024',
    country: 'Egypt',
    industry: 'Sports & Fitness',
    stack: ['WordPress', 'WooCommerce'],
    tags: ['Web Dev', 'WordPress', 'Ecommerce'],
    summary: 'Sports and fitness e-commerce website for Peak Pulse, a multi-sport training facility with an online merchandise shop.',
    challenge: 'Peak Pulse needed a site that could represent multiple sports disciplines, sell branded merchandise, and handle class bookings — all in one cohesive platform.',
    solution: 'Built a high-energy WordPress site with WooCommerce integration for the merch shop, clear sport-category navigation, and a services section covering boxing, jiu-jitsu, personal training, and nutrition.',
    results: [
      'Multi-sport service architecture with dedicated pages per discipline',
      'E-commerce shop live at launch with product catalogue',
      'Mobile-first design matching the brand energy',
    ],
  },
  {
    slug: 'gripnclimb',
    title: "Grip 'n' Climb",
    subtitle: 'Climbing & Adventure · Sydney, Australia · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/gripnclimb.jpg',
    url: 'https://gripnclimb.com/',
    year: '2024',
    country: 'Australia',
    industry: 'Adventure & Recreation',
    stack: ['WordPress', 'Booking Plugin'],
    tags: ['Web Dev', 'WordPress', 'Booking'],
    summary: "Website and online booking system for Grip 'n' Climb, a climbing and adventure facility in Sydney.",
    challenge: 'Building a site that communicates the excitement of climbing while handling complex booking flows for classes, sessions, and birthday parties.',
    solution: 'Developed a bold WordPress site with integrated booking capabilities, event listings, gallery sections, and a birthday party packages module.',
    results: [
      'Online bookings replacing phone-only reservations',
      'Birthday party package landing pages driving conversions',
      'Full mobile experience matching the adventure brand',
    ],
  },
  {
    slug: 'hana-makhlouf',
    title: 'Hana Makhlouf',
    subtitle: 'Personal Brand · International · 2026',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/hana-makhlouf.jpg',
    url: 'https://hanamakhlouf.me/',
    year: '2026',
    country: 'International',
    industry: 'Personal Brand',
    stack: ['WordPress'],
    tags: ['Web Dev', 'WordPress', 'Personal Website'],
    summary: 'Personal website for Hana Makhlouf — career coach, CV reviewer, and author — built to centralise her brand and services.',
    challenge: 'Consolidating multiple offerings (career coaching, book notes, blog, CV reviews) into one clean, navigable personal site that reflects her professional credibility.',
    solution: 'Built a minimal, fast WordPress site with clear content sections for services, blog, book notes, and resources — optimised for personal brand authority.',
    results: [
      'All services and content channels under one roof',
      'Blog and resource library driving repeat traffic',
      'Clean personal brand aesthetic matching her coaching style',
    ],
  },
  {
    slug: 'fmguni',
    title: 'FMG Uni',
    subtitle: 'Online Education · International · 2026',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/fmguni.jpg',
    url: 'http://fmguni.com/',
    year: '2026',
    country: 'International',
    industry: 'E-Learning',
    stack: ['WordPress', 'LearnDash'],
    tags: ['Web Dev', 'WordPress', 'LMS'],
    summary: 'LMS-powered university portal for FMG Uni, offering structured academic courses and certifications online.',
    challenge: 'Creating a credible, university-grade online learning environment with proper course structure, student progress tracking, and certification.',
    solution: 'Built a WordPress + LearnDash LMS platform with an institution-level design, full course catalogue, and student management system.',
    results: [
      'University-grade LMS platform operational at launch',
      'Multiple courses with structured lesson flow',
      'Professional design elevating the institution credibility',
    ],
  },
  {
    slug: 'pioneers-me',
    title: 'Pioneers ME',
    subtitle: 'Marketing Agency · Cairo, Egypt · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/pioneers-me.jpg',
    url: 'https://www.pioneersme.com/',
    year: '2024',
    country: 'Egypt',
    industry: 'Marketing & Advertising',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Agency website for Pioneers ME, a full-service marketing and activation agency based in Cairo.',
    challenge: 'A marketing agency with an impressive portfolio needed a website that could match their positioning — dynamic, visual, and capable of showcasing their diverse work.',
    solution: 'Developed a portfolio-led WordPress site with animated section transitions, a structured services overview, and a dedicated work showcase module.',
    results: [
      'Portfolio of 10+ campaign types displayed on launch',
      'Agency-grade visual presentation matching competitors',
      'New business inquiries via website within first month',
    ],
  },
  {
    slug: 'passion-it-media',
    title: 'Passion-IT Media',
    subtitle: 'Media & Content · Cairo, Egypt · 2025',
    category: 'web design',
    cat: 'Web & Design',
    image: '/work/passion-it-media.jpg',
    url: 'https://passionit-media.com/',
    year: '2025',
    country: 'Egypt',
    industry: 'Media & Content',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Media company website for Passion-IT Media, a Cairo-based content and digital media studio.',
    challenge: 'Building a creative agency site that reflects innovation and media savvy while being structured enough to communicate their service offering clearly.',
    solution: 'Developed a bold WordPress site that balances visual energy with service clarity — featuring a media portfolio, services breakdown, and client case studies.',
    results: [
      'Creative agency positioning clearly communicated',
      'Client portfolio showcased on launch',
      'Site matching the media and content industry aesthetic',
    ],
  },
  {
    slug: 'swim-eagles',
    title: 'Swim Eagles',
    subtitle: 'Sports Academy · Cairo, Egypt · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/swim-eagles.png',
    year: '2024',
    country: 'Egypt',
    industry: 'Sports Academy',
    stack: ['WordPress', 'Elementor'],
    tags: ['Web Dev', 'WordPress'],
    summary: 'Website for Swim Eagles, a competitive swimming academy based in Cairo, serving youth and professional swimmers.',
    challenge: 'Swim Eagles needed a website that could communicate their training programmes, coaching team, and registration process to parents and athletes.',
    solution: 'Built a clean, energetic WordPress site with programme details, coaching profiles, and a registration call-to-action optimised for mobile.',
    results: [
      'Training programmes clearly structured by level and age group',
      'Coach profiles building parent trust',
      'Mobile-first design for easy access by parents on the go',
    ],
  },
  {
    slug: 'ghoz-designs',
    title: 'Ghoz Designs',
    subtitle: 'Fashion E-commerce · Cairo, Egypt · 2024',
    category: 'web',
    cat: 'Web & Technology',
    image: '/work/amc-group.jpg',   // placeholder until screenshot available
    year: '2024',
    country: 'Egypt',
    industry: 'Fashion & E-commerce',
    stack: ['WordPress', 'WooCommerce'],
    tags: ['Web Dev', 'WordPress', 'Ecommerce'],
    summary: 'Fashion e-commerce store for Ghoz Designs, a Cairo-based clothing and accessories brand.',
    challenge: 'Launching an e-commerce operation from zero — product catalogue, payment processing, inventory management, and a brand-aligned storefront.',
    solution: 'Built a full WooCommerce store with product gallery, size guides, secure checkout, and a visual brand language consistent with the fashion positioning.',
    results: [
      'Full e-commerce operation launched end-to-end',
      'Product catalogue live with clean visual layout',
      'Secure payment processing integrated at launch',
    ],
  },
  {
    slug: 'combat-wear',
    title: 'Combat Wear',
    subtitle: 'Combat Sports Apparel · Cairo, Egypt · 2025',
    category: 'web branding',
    cat: 'Web & Branding',
    image: '/work/combat-wear.jpg',
    year: '2025',
    country: 'Egypt',
    industry: 'Sports Apparel',
    stack: ['WordPress', 'WooCommerce'],
    tags: ['Web Dev', 'WordPress', 'Ecommerce', 'Branding'],
    summary: 'Brand identity and e-commerce website for Combat Wear, a combat sports apparel brand launching in the Egyptian market.',
    challenge: 'Combat Wear needed a full brand identity built from scratch alongside an e-commerce store that could launch simultaneously with the product line.',
    solution: 'Delivered the complete brand system — logo, typography, colour palette, brand guidelines — and built a WooCommerce store with product photography integration and a premium apparel aesthetic.',
    results: [
      'Brand identity and e-commerce launched together',
      'Premium apparel aesthetic standing out in local market',
      'Gift cards, size charts, and product pages fully operational',
    ],
  },
]

export function getProject(slug: string): Project | undefined {
  return PROJECTS.find(p => p.slug === slug)
}

export function getAllSlugs(): string[] {
  return PROJECTS.map(p => p.slug)
}
